# docker-compose.yml
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - db-net

  web:
    build: ./backend
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - db-net
      - app-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
    depends_on:
      - db
    networks:
      - db-net
      - app-net

volumes:
  db-data:
  
networks:
  db-net:
    internal: true
  app-net:
